name: Yolk - Reusable Docker Build

on:
  workflow_call:
    inputs:
      build_name:
        required: true
        type: string
      build_path:
        required: true
        type: string
      ocr_login:
        required: false
        type: boolean
    secrets:
      ocr_username:
        required: false
      ocr_password:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: ${{ inputs.build_name }}

      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@v3
        if: inputs.ocr_login
        with:
          registry: container-registry.oracle.com
          username: ${{ secrets.ocr_username }}
          password: ${{ secrets.ocr_password }}

      - name: Temporary fix
        run: |
          cd ${{ inputs.build_path }}
          cp ../entrypoint.sh .

      - uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build_path }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
