name: Java - Build

on:
  push:
    branches:
      - main
    paths:
      - Java/**
  pull_request:
    branches:
      - main
    paths:
      - Java/**
  workflow_dispatch: {}

jobs:
  build:
    name: ${{ matrix.name }}
    uses: ./.github/workflows/docker-build.yml
    with:
      build_name: ${{ matrix.name }}
      build_path: ${{ matrix.path }}
      ocr_login: true
    secrets:
      ocr_username: ${{ secrets.OCR_USERNAME }}
      ocr_password: ${{ secrets.OCR_PASSWORD }}

    strategy:
      matrix:
        include:
          - name: "java_8"
            path: "Java/GraalVM/8"
          - name: "java_11"
            path: "Java/GraalVM/11"
          - name: "java_17"
            path: "Java/GraalVM/17"
