name: Java - GraalVM LazyMC Build

on:
  push:
    branches:
      - main
    paths:
      - Java/GraalVM-LZ/**
  pull_request:
    branches:
      - main
    paths:
      - Java/GraalVM-LZ/**
  workflow_dispatch: {}

jobs:
  build:
    name: ${{ matrix.name }}
    uses: ./.github/workflows/docker-build.yml
    with:
      build_name: ${{ matrix.name }}
      build_path: "Java/GraalVM-LZ"
      ocr_login: true
    secrets:
      ocr_username: ${{ secrets.OCR_USERNAME }}
      ocr_password: ${{ secrets.OCR_PASSWORD }}

    strategy:
      matrix:
        include:
          - name: "graalvm_lz_java_8"
            version: "ol9-java8-21"
          - name: "graalvm_lz_java_11"
            version: "ol9-java11-22"
          - name: "graalvm_lz_java_17"
            version: "ol9-java17-22"