name: Java - GraalVM Build

on:
  push:
    branches:
      - main
    paths:
      - Java/GraalVM/**
  pull_request:
    branches:
      - main
    paths:
      - Java/GraalVM/**
  workflow_dispatch: {}

jobs:
  build:
    name: ${{ matrix.name }}
    uses: ./.github/workflows/docker-build.yml
    with:
      build_name: ${{ matrix.name }}
      build_path: "Java/GraalVM"
      image_version: ${{ matrix.version }}
      image_source: ${{ matrix.source }}
      ocr_login: true
    secrets:
      ocr_username: ${{ secrets.OCR_USERNAME }}
      ocr_password: ${{ secrets.OCR_PASSWORD }}

    strategy:
      matrix:
        include:
          - name: "graalvm_java_8"
            source: "container-registry.oracle.com/graalvm/jdk-ee"
            version: "ol9-java8-21"
          - name: "graalvm_java_11"
            source: "container-registry.oracle.com/graalvm/jdk-ee"
            version: "ol9-java11-22"
          - name: "graalvm_java_17"
            source: "container-registry.oracle.com/graalvm/jdk-ee"
            version: "ol9-java17-22"
