name: Java Build

on:
  push:
    branches:
      - main
    paths:
      - Java/**
  pull_request:
    branches:
      - main
    paths:
      - Java/**
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      build_name: ${{ matrix.name }}
      build_path: ${{ matrix.path }}
      ocr_login: true
    secrets:
      username: ${{ secrets.OCR_USERNAME }}
      password: ${{ secrets.OCR_PASSWORD }}

    strategy:
      matrix:
        include:
          - name: "java_8"
            path: "Java/GraalVM/8"
          - name: "java_11"
            path: "Java/GraalVM/11"
          - name: "java_17"
            path: "Java/GraalVM/17"
